# Generated by Django 5.1 on 2024-08-21 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('track', '0001_initial'),
        ('trainee', '0002_trainee_trackobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('trackobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.track')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTrainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
                ('traineeobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainee.trainee')),
            ],
        ),
    ]
