# Generated by Django 5.1 on 2024-08-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='img',
            field=models.ImageField(null=True, upload_to='trainee/images'),
        ),
    ]
