# Generated by Django 5.1 on 2024-08-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_trainee_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='trainee/images'),
        ),
    ]
